### ISSUE TITLE
InventoryCreativeEvent

### ISSUE THREAD

**Issue by ChansinTech** [badbones69/Crazy-Enchantments#153]
I just updated to the most recent version of the plugin, but I get this error when I apply an enchantment while in Creative mode: `[Server thread/ERROR]: Could not pass event InventoryCreativeEvent to CrazyEnchantments v1.7.5.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:2001) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-c55900f-9856d8a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[spigot.jar:git-Spigot-c55900f-9856d8a]
	at me.BadBones69.CrazyEnchantments.Methods.color(Methods.java:47) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.ScrollControl.getTransmogScroll(ScrollControl.java:242) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.ScrollControl.onScrollUse(ScrollControl.java:49) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-c55900f-9856d8a]
	... 15 more
[12:22:19]`

**Comment by kicjow** [comment]
Please read the update and add the new lines it tells you to.
https://www.spigotmc.org/resources/crazy-enchantments-new-gkitz.16470/update?update=137823

**Comment by diamond-sword51** [comment]
I tried adding in the lines but it still didn't work for me,[ here is my config ](http://pastebin.com/PVAbEhZE)(pre additons). Please could you help?

Thanks
-diamond_sword51

**Comment by kicjow** [comment]
@diamond-sword51 You didn't add any of the new lines like it said to. Please next time read the change log and add the new lines.
https://hastebin.com/wozujewele.php

**Comment by diamond-sword51** [comment]
I had added the lines before but it just wouldn't reload via a server restart or the command so i posted the save pre-line addition so I was the same as this thread

**Comment by kicjow** [comment]
@diamond-sword51 Did that fix it for you?

**Comment by phamductrungbmt** [comment]
I get this error https://hastebin.com/qomotobizo.bash and here is config.yml: https://hastebin.com/axozoxusiy.php
