### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by 1326745** [badbones69/Crazy-Enchantments#167]
I dont know why this is happening but whenever i throw an xp bottle this code occurs:

[07:03:54] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to CrazyEnchantments v1.7.6.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:745) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.EntityProjectile.s_(EntityProjectile.java:156) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.World.entityJoinedWorld(World.java:1604) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.World.g(World.java:1579) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1422) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:576) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:772) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
	at me.BadBones69.CrazyEnchantments.multisupport.WorldGuard.allowsPVP(WorldGuard.java:15) ~[?:?]
	at me.BadBones69.CrazyEnchantments.multisupport.Support.allowsPVP(Support.java:187) ~[?:?]
	at me.BadBones69.CrazyEnchantments.API.CustomEnchantments.onland(CustomEnchantments.java:233) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]

---------------------------------------------------------------

Whenever I try to get a book from /ce this code occurs:

[07:06:01] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.6.3.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_111]
	at me.BadBones69.CrazyEnchantments.Controlers.EnchantmentControl.powerPicker(EnchantmentControl.java:378) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.EnchantmentControl.Enchants(EnchantmentControl.java:39) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.EnchantmentControl.pick(EnchantmentControl.java:338) ~[?:?]
	at me.BadBones69.CrazyEnchantments.Controlers.ShopGUI.onInvClick(ShopGUI.java:207) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]

**Comment by 1326745** [comment]
Enchantments.yml
http://pastebin.com/SDpSBYMU

Config.yml
http://pastebin.com/tNZ5yyNM

**Comment by SilverHuskey** [comment]
The only issue i found is this:

REMOVE LINES WITH THE # DO THIS ON ALL ENCHANTMENTS

  Necromancer:
    Enabled: True
    Name: 'Necromancer'
    Color: '&7'
    BookColor: '&a&l'
    MaxPower: 3
    Info:
      Name: '&a&lNecromancer &7(&fI-&fIII&7)'
      Description:
        - '&7Spawns in zombies'
        - '&7when you are in trouble.'
 #       - ''              **-This value does nothing therefore it may be throwing a few errors here and there**
 #
        - '&7Enchantable Items: &eArmor'
    Categories:
      - 'Rare'

**Comment by SilverHuskey** [comment]
Your lines that state this - '' Are causing some issues. it may not be related to this issue but it may cause other issues
  
Necromancer:
    Enabled: True
    Name: 'Necromancer'
    Color: '&7'
    BookColor: '&a&l'
    MaxPower: 3
    Info:
      Name: '&a&lNecromancer &7(&fI-&fIII&7)'
      Description:
        - '&7Spawns in zombies'
        - '&7when you are in trouble.'
        - ''
 
        - '&7Enchantable Items: &eArmor'
    Categories:
      - 'Rare'
