### ISSUE TITLE
loading ce

### ISSUE THREAD

**Issue by XxMrWolfxX** [badbones69/Crazy-Enchantments#211]
[22:11:24 INFO]: [CrazyEnchantments] Enabling CrazyEnchantments v1.7.9.1
[22:11:24 ERROR]: Error occurred while enabling CrazyEnchantments v1.7.9.1 (Is it up to date?)
java.lang.NullPointerException
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at me.badbones69.crazyenchantments.Methods.makeItem(Methods.java:459) ~[?:?]
        at me.badbones69.crazyenchantments.api.DataStorage.getInfoGKit(DataStorage.java:174) ~[?:?]
        at me.badbones69.crazyenchantments.api.DataStorage.load(DataStorage.java:47) ~[?:?]
        at me.badbones69.crazyenchantments.Main.onEnable(Main.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:396) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:364) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:319) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:215) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:540) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by XxMrWolfxX** [comment]
and with /ce

[22:13:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin CrazyEnchantments v1.7.9.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1116) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:748) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:320) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:686) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:589) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.badbones69.crazyenchantments.api.currencyapi.CurrencyAPI.getCurrency(CurrencyAPI.java:18) ~[?:?]
        at me.badbones69.crazyenchantments.controlers.ShopControler.openGUI(ShopControler.java:49) ~[?:?]
        at me.badbones69.crazyenchantments.Main.onCommand(Main.java:194) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        ... 14 more

**Comment by XxMrWolfxX** [comment]
can anyone help me Please?

**Comment by kicjow** [comment]
It seems your trying to use the Vault currency without having vault installed.
