### ISSUE TITLE
Error occurred while enabling

### ISSUE THREAD

**Issue by MiniEyez** [badbones69/Crazy-Enchantments#216]
` at me.badbones69.crazyenchantments.Main.onEnable(Main.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`
`[13:40:08 ERROR]: Error occurred while enabling CrazyEnchantments v1.7.9.1 (Is it up to date?)`

**Comment by kicjow** [comment]
Is there anymore to that error? If so can you please pastebin the full thing.
