### ISSUE TITLE
Error when clicking in a GUI

### ISSUE THREAD

**Issue by zRiaz** [badbones69/Crazy-Enchantments#218]
`[21:22:53] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CrazyEnchantments v1.7.9.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot.jar:git-PaperSpigot-"8b18730"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324) ~[paperspigot.jar:git-PaperSpigot-"8b18730"]
	at me.badbones69.crazyenchantments.Methods.color(Methods.java:52) ~[?:?]
	at me.badbones69.crazyenchantments.controlers.ShopControler.infoClick(ShopControler.java:426) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paperspigot.jar:git-PaperSpigot-"8b18730"]
	... 16 more`
The following error is being thrown out by CrazyEnchantments everytime I click on the GUI from FactionsTop. (https://www.spigotmc.org/resources/f-top-factions-top-by-novucs.26905/)

**Comment by ISanderI** [comment]
This actually accures every time a GUI is being clicked, no matter which plugin.

**Comment by ISanderI** [comment]
Also actually happens when clicking inside CE's GUI aswell. Basically happens on every single inventory click event from a plugin.

**Comment by kicjow** [comment]
Seems something is missing or broke in the config.yml. Can you pastebin the config and send the URL.
