### ISSUE TITLE
Lostbooks are giving me nothing.... [HELP]

### ISSUE THREAD

**Issue by ThestralMoon** [badbones69/Crazy-Enchantments#262]
Hi!
Whenever I try to open a lostbook from the unique category it doesn't work. It gives me nothing.
the config.yml is here attached

https://hastebin.com/aponeyopis.bash

**Comment by Jnxd1** [comment]
Hastebin.com

**Comment by ThestralMoon** [comment]
https://hastebin.com/juwufivayo.bash

**Comment by ThestralMoon** [comment]
HELLO!?

**Comment by ThestralMoon** [comment]
someone please help
0

**Comment by UnrealisticBeing** [comment]
Make sure you @ mention me so I'm emailed a response....

Include a hastebin or pastebin of the file you already included above, and another one of the file with your enchantments.

**Comment by UnrealisticBeing** [comment]
And send me another hastebin that's directly copied from your config.yml. That one above is missing indentation

**Comment by UnrealisticBeing** [comment]
If you want better help add me on discord @UnrealisticBeing#9314

**Comment by ThestralMoon** [comment]
@UnrealisticBeing 
The Config: https://hastebin.com/aponeyopis.bash
The Enchantments: https://hastebin.com/fuyexinuva.php

**Comment by ThestralMoon** [comment]
@kicjow Please Help

**Comment by ThestralMoon** [comment]
Bump

**Comment by ThestralMoon** [comment]
@kicjow @UnrealisticBeing Please Help. This Is The Error I Recieve In My Server Console:
`org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_112]
        at me.badbones69.crazyenchantments.controlers.EnchantmentControl.powerPicker(EnchantmentControl.java:416) ~[?:?]
        at me.badbones69.crazyenchantments.controlers.EnchantmentControl.getRandomEnchantment(EnchantmentControl.java:45) ~[?:?]
        at me.badbones69.crazyenchantments.controlers.EnchantmentControl.pick(EnchantmentControl.java:378) ~[?:?]
        at me.badbones69.crazyenchantments.controlers.LostBook.onBookClean(LostBook.java:56) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-1daee53]
        ... 17 more`
