### ISSUE TITLE
I'm getting my console spammed with errors such as these

### ISSUE THREAD

**Issue by zenandreas** [badbones69/Crazy-Enchantments#343]
`[13:27:03 ERROR]: Could not pass event PlayerDeathEvent to CrazyEnchantments v1.7.9.3.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:434) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:493) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:799) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:622) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.BlockCactus.a(BlockCactus.java:98) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.IBlockData.a(SourceFile:269) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:940) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:852) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:1950) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityHuman.a(EntityHuman.java:1502) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityLiving.k(EntityLiving.java:2285) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityHuman.k(EntityHuman.java:407) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2100) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:151) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:381) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:140) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f6a273b-8ab46ff]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/WGBukkit
        at me.badbones69.crazyenchantments.multisupport.WorldGuard.allowsPVP(WorldGuard.java:14) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.Support.allowsPVP(Support.java:138) ~[?:?]
        at me.badbones69.crazyenchantments.enchantments.Swords.onPlayerDeath(Swords.java:417) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-f6a273b-8ab46ff]
        ... 27 more
`

**Comment by Leomelonseeds** [comment]
The problem is with worldguard. It either doesn't support 1.13 or the crazyenchantments plugin does not support worldguard.
