### ISSUE TITLE
New async blast crashing server

### ISSUE THREAD

**Issue by pmme** [badbones69/Crazy-Enchantments#359]
I've built based on your v1.8 branch with a few changes at my end. This includes your recent change to make blast async. However on our server that's causing a crash. Seems bukkit isn't so keen on the async entity add and async effect add.

<pre>
[17:11:43] [Craft Scheduler Thread - 612/ERROR]: Could not pass event BlockBreakEvent to mcMMO v2.1.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at me.badbones69.crazyenchantments.enchantments.PickAxes$1.run(PickAxes.java:98) [crazyenchantments-1.8-CSMC.5.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Asynchronous entity add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.World.addEntity(World.java:901) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.WorldServer.addEntity(WorldServer.java:917) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.dropItem(CraftWorld.java:315) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at com.gmail.nossr50.util.Misc.dropItem(Misc.java:125) ~[mcMMO.jar:?]
	at com.gmail.nossr50.util.Misc.dropItems(Misc.java:88) ~[mcMMO.jar:?]
	at com.gmail.nossr50.skills.mining.Mining.handleMiningDrops(Mining.java:157) ~[mcMMO.jar:?]
	at com.gmail.nossr50.skills.mining.MiningManager.miningBlockCheck(MiningManager.java:87) ~[mcMMO.jar:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:226) ~[mcMMO.jar:?]
	at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	... 9 more
[17:11:43] [Craft Scheduler Thread - 612/ERROR]: Could not pass event BlockBreakEvent to CrazyEnchantments v1.8-CSMC.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at me.badbones69.crazyenchantments.enchantments.PickAxes$1.run(PickAxes.java:98) [crazyenchantments-1.8-CSMC.5.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException: Asynchronous effect add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at net.minecraft.server.v1_13_R2.EntityLiving.addEffect(EntityLiving.java:737) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:289) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:279) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	at me.badbones69.crazyenchantments.enchantments.Tools.updateEffects(Tools.java:189) ~[crazyenchantments-1.8-CSMC.5.jar:?]
	at me.badbones69.crazyenchantments.enchantments.Tools.onBlockBreak(Tools.java:52) ~[crazyenchantments-1.8-CSMC.5.jar:?]
	at sun.reflect.GeneratedMethodAccessor294.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-f56e2e7-7fc66b2]
	... 9 more
</pre>

**Comment by pmme** [comment]
Ceased crashing in one of the dev builds (v4, v5?).
Don't actually know what the problem was but happy it's working fine now.
