### ISSUE TITLE
report about bugs plugins Crazy Enchantments

### ISSUE THREAD

**Issue by shelex1** [badbones69/Crazy-Enchantments#379]
Crazy Enchantments no work Interface GUI
![image](https://user-images.githubusercontent.com/50044311/56847617-8e9f4180-6907-11e9-9f6f-1a6ce340a3b4.png)
And next text write console:
[09:14:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin CustomEnchants v1.13.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1340) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1200) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.NoSuchFieldError: LEGACY_DIAMOND_SPADE
	at me.jupdyke01.CustomInventories.MainInventory.EnchantInventory(MainInventory.java:71) ~[?:?]
	at me.jupdyke01.CustomInventories.MainInventory.onCommand(MainInventory.java:154) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.12.2.jar:git-Bukkit-e60fc34]
	... 15 more

**Comment by badbones69** [comment]
Not an error from my plugin.
This is not mine: Unhandled exception executing command 'ce' in plugin CustomEnchants v1.13.3
