### ISSUE TITLE
Error with right click

### ISSUE THREAD

**Issue by PhanaticD** [badbones69/Crazy-Enchantments#442]
using build 35 of CE on a 1.14.4 server

```
[14:31:57 ERROR]: Could not pass event PlayerInteractEvent to CrazyEnchantments v1.8-Dev-Build-v7.1-Build#35
java.lang.ArrayIndexOutOfBoundsException: -1
        at me.badbones69.crazyenchantments.api.CrazyEnchantments.getEnchantmentsOnItem(CrazyEnchantments.java:884) ~[?:?]
        at me.badbones69.crazyenchantments.enchantments.Hoes.onInteract(Hoes.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor99.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[bvival.jar:git-Purpur-295]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[bvival.jar:git-Purpur-295]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[bvival.jar:git-Purpur-295]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[bvival.jar:git-Purpur-295]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:454) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:441) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1425) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1036) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1029) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1013) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:936) ~[bvival.jar:git-Purpur-295]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by badbones69** [comment]
Thanks for the report. I just fixed the issue.
181e3c9284edaebffdc6a4792803b4ebe94905ce
