### ISSUE TITLE
[Bug Report] java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by bobhenl** [badbones69/Crazy-Enchantments#576]
**Describe the bug**

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.16.5
 - Plugin Version: v1.8-Dev-Build-v8.1-SNAPSHOT-Build#164

**Pastebin any errors in console**
Link: https://pastebin.com/hM2CSBWP & https://pastebin.com/R90C96fL

**Issue**
I got some error and then really big spam, about 200+ lines of the latest line mentioned on pastebin.

**Screenshots**
Player used /sf give ProchynQa ANCIENT_RUNE_SOULBOUND, so it is probably related to it. I tested myself and happened again.

**Comment by Yukun99** [comment]
Does your player have the soulbound rune applied on hellforged armour by any chance

**Comment by bobhenl** [comment]
No I didn't work.Also getting this one:
```
[17:04:13] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CrazyEnchantments v1.8-Dev-Build-v8.1-SNAPSHOT-Build#164
java.lang.NullPointerException: null
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.hasEnchantment(CrazyEnchantments.java:562) ~[?:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.getUpdatedEffects(CrazyEnchantments.java:1015) ~[?:?]
	at me.badbones69.crazyenchantments.api.CrazyEnchantments.updatePlayerEffects(CrazyEnchantments.java:976) ~[?:?]
	at me.badbones69.crazyenchantments.Main.onPlayerJoin(Main.java:127) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor786.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-7]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-7]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:168) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:176) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1468) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1287) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.5.jar:git-Yatopia-7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```


Then when joining with this enchant:
```
  #Do not change this line.
  AntiGravity:
    Enabled: true
    Name: 'Bez limitu'
    Color: '&7'
    BookColor: '&e'
    MaxPower: 3
    Enchantment-Type: 'Boots'
    Info:
      Name: '&e&lBez limitu &7(&bI-&bIII&7)'
      Description:
        - '&7Při nošení rapidně'
        - '&7zvýší skoky'
        - ''
        - '&6Kategorie:'
        - '&7 - &a&l&nBěžná'
        - '&7 - &9&l&nVzácná'
        - '&7 - &6&l&nLegendární'
        - '&6Možno očarovat: &aBoty'
    Categories:
      - 'Common'
      - 'Rare'
      - 'Legendary'
```
Error is thrown:
```
[17:33:40 WARN]: [CrazyEnchantments] Plugin CrazyEnchantments v1.8-Dev-Build-v8.1-SNAPSHOT-Build#164 generated an exception while executing task 7394286
java.lang.NullPointerException: null
> 
```
-> didn't happen on older builds few days ago (max 7 week).

Also these didn't work for me and probably are causing issue:
```
  Ninja:
    Enabled: true
    Name: 'Ninja'
    Color: '&7'
    BookColor: '&e'
    MaxPower: 2
    Enchantment-Type: 'Armor'
    Info:
      Name: '&e&lNinja &7(&bI-&bII&7)'
      Description:
        - '&7Při nošení dá rychlost'
        - '&7a odolnost ninji.'
        - ''
        - '&6Kategorie:'
        - '&7 - &a&l&nBěžná'
        - '&7 - &9&l&nVzácná'
        - '&7 - &6&l&nLegendární'
        - '&6Možno očarovat: &aZbroje'
    Categories:
      - 'Common'
      - 'Rare'
      - 'Legendary'
```
```
  OverLoad:
    Enabled: true
    Name: 'Zdraví'
    Color: '&7'
    BookColor: '&e'
    MaxPower: 5
    Enchantment-Type: 'Armor'
    Info:
      Name: '&e&lZdraví &7(&bI-&bV&7)'
      Description:
        - '&7Při nošení dá pár'
        - '&7srdíček navíc.'
        - ''
        - '&6Kategorie:'
        - '&7 - &a&l&nBěžná'
        - '&7 - &9&l&nVzácná'
        - '&7 - &6&l&nLegendární'
        - '&6Možno očarovat: &aZbroje'
    Categories:
      - 'Common'
      - 'Rare'
      - 'Legendary'
```
```
  Necromancer:
    Enabled: true
    Name: 'Vyvolávač'
    Color: '&7'
    BookColor: '&e'
    MaxPower: 3
    Enchantment-Type: 'Armor'
    Info:
      Name: '&e&lVyvolávač &7(&bI-&bIII&7)'
      Description:
        - '&7Při nošení a objevení se'
        - '&7v úzkých přivolá na pomoc'
        - '&7nemrtvé.'
        - ''
        - '&6Kategorie:'
        - '&7 - &9&l&nVzácná'
        - '&7 - &6&l&nLegendární'
        - '&6Možno očarovat: &aZbroje'
    Categories:
      - 'Rare'
      - 'Legendary'
```


FOR now I'll downgrade to older build.

**Comment by bobhenl** [comment]
Trying old builds and now getting:
```
[18:59:03 WARN]: [CrazyEnchantments] Plugin CrazyEnchantments v1.8-Dev-Build-v8.1-SNAPSHOT-Build#162 generated an exception while executing task 38141
java.lang.NullPointerException: null
        at me.badbones69.crazyenchantments.api.CrazyEnchantments.hasEnchantments(CrazyEnchantments.java:546) ~[?:?]
        at me.badbones69.crazyenchantments.enchantments.Armor$4.run(Armor.java:413) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Yatopia-7]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Yatopia-7]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Yatopia-7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
